name: Build Plugin

on:
  workflow_call:
    inputs:
      version:
        required: false
        type: string

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore
        run: dotnet restore

      - name: Build Debug
        run: dotnet build --configuration Debug /p:GitVersion=${{ inputs.version }}

      - name: Build Release
        run: dotnet build --configuration Release /p:GitVersion=${{ inputs.version }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-artifacts
          path: |
            **/bin/Debug/*
            **/bin/Release/*
